### ISSUE TITLE
make this api-client compatible with umami 2.9.0 

### ISSUE THREAD

**Issue by boly38** [jakobbouchard/umami-api-client#84]
hi, the goal is to make this api-client compatible with umami 2.9.0 

there is an helper with the following ticket
boly38/umami-api-client#15

Bonus: it could be over-mega-great to add a "CONTRIBUTE.md" helper in order to help (this) api-client users to install/build current source. I miss how to install requirement to play unit tests for example an confirm my hypothesis.

(anyway it seems that `/api/websites` **`data` level** in `2.x` umami responses are not undertaken here.)

Nb: notice this related issue on umami doc side: umami-software/website#150

thanks 👍

**Comment by imjuniper** [comment]
Hey! I would love to add support for umami 2.x, but it's quite time-demanding due to their documentation being out of date. I usually have to reverse-engineer it by reading everything in the folders. Since I'm in my last university semester, I'm really busy lately. I also don't really use umami anymore, so it's a bit harder to test (usually I spin up a local docker container). If you could make a PR for it, it would be great! If you can't that's fine, but I can't guarantee when I'll be able to update it 😅 

I had started work on it a while ago, so I might be able to push a branch with it started too. I'll see if I still have it around.

**Comment by imjuniper** [comment]
Hello! :wave: I no longer work in web development, and do not have a lot of free time or interest in maintaining this package anymore. I am closing all issues and PR for it and will archive the repository, but if anybody is interested in maintaining it, I am willing to transfer the repository and NPM package. I know you had been using this package for a while, sorry that I can't maintain it anymore!
